config/routes.rb
Rails.application.routes.draw do
  get "terms", to: "pages#terms"
  get "privacy", to: "pages#privacy"
  get "disclaimer", to: "pages#disclaimer"
  get "noscript", to: "pages#noscript"

  namespace :finder, module: :finders do
    resources :users, only: [:index]
  end

  devise_for :users, path: "sudo", controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  resources :pods, only: [:create, :destroy] do
    resources :attachments, only: [:create], module: :pods
    resources :comments, only: [:create], module: :pods
    resource :reaction, only: [:create, :destroy], module: :pods
  end

  resources :comments, only: [:destroy] do
    resource :reaction, only: [:create, :destroy], module: :comments
  end

  namespace :me do
    resource :avatar, only: [:create, :update, :edit]
    resource :cover, only: [:create]
  end

  scope ":username", as: :user, module: :profiles do
    resource :followers, only: [:show]
    resource :following, only: [:show], controller: :following
    resource :relationship, only: [:create, :destroy]
    resources :pods, only: [:show]
    root "profile#show", as: :profile
  end

  authenticated :user do
    root "home#show"
  end

  root to: "welcome#index"
end

app/models/avatar.rb
class Avatar
  include ActiveModel::Model
  attr_accessor :image

  validates :image, presence: true

  def attach(user)
    if valid?
      user.original.attach(image)
      true
    else
      false
    end
  end
end

app/controllers/me/avatars_controller.rb
class Me::AvatarsController < ApplicationController
  before_action :authenticate_user!

  def create
    @avatar = Avatar.new(avatar_params)

    if @avatar.attach(current_user)
      redirect_to edit_me_avatar_path, notice: t(".notice")
    else
      redirect_to edit_user_registration_path, alert: t(".alert")
    end
  end

  def edit
    unless current_user.original.attached?
      redirect_to edit_user_registration_path, alert: t(".alert")
    end
  end

  def update
    current_user.avatar.attach(avatar_params[:image])

    if current_user.avatar.attached?
      redirect_to edit_user_registration_path, notice: t(".notice")
    else
      redirect_to edit_user_registration_path, alert: t(".alert")
    end
  end

  private

    def avatar_params
      params.require(:avatar).permit(:image)
    end
end

app/controllers/me/covers_controller.rb
class Me::CoversController < ApplicationController
  before_action :authenticate_user!

  rescue_from ActionController::ParameterMissing do
    redirect_to edit_user_registration_path, alert: t(".missing")
  end

  def create
    @cover = Cover.new(cover_params)

    if @cover.attach(current_user)
      redirect_to edit_user_registration_path, notice: t(".notice")
    else
      redirect_to edit_user_registration_path, notice: t(".alert")
    end
  end

  private

    def cover_params
      params.require(:cover).permit(:image)
    end
end

app/helpers/avatar_helper.rb
module AvatarHelper
  def user_avatar(user, options = nil)
    options ||= {}
    html = options.delete(:html) || {}
    if user.avatar.attached?
      src = user.avatar.variant(options)
    else
      src = "https://www.gravatar.com/avatar/1da67f9c292299c7512d9f0dc2c13f04?s=256&d=mm"
    end
    image_tag(src, html)
  end

  def avatar_url(user, options = nil)
    if user.avatar.attached? && options.present?
      user.avatar.variant(options)
    elsif user.avatar.attached?
      user.avatar
    else
      "https://www.gravatar.com/avatar/1da67f9c292299c7512d9f0dc2c13f04?s=256&d=mm"
    end
  end
end

app/views/me/avatars/_form.html.slim
div id="user_avatar_viewer" class="avatar-big-wrapper mb-4 d-block border rounded-circle mx-auto"
  = image_tag avatar_url(current_user), class: "rounded-circle img-fluid"

= form_for(Avatar.new, url: me_avatar_path, data: { controller: "avatar" }) do |f|
  div class="avatar-control"
    label class="btn btn-success mb-0" data-target="avatar.label"
      = t(".avatar.change")
      = f.file_field :image,
        direct_upload: true,
        hidden: true,
        accept: "image/x-png,image/jpeg",
        data: { action: "avatar#onPickImage", target: "avatar.image" }

    - if current_user.original.attached?
      = link_to t(".avatar.resize"), edit_me_avatar_path, class: "btn btn-outline-primary ml-2", data: { turbolinks: false, target: "avatar.crop" }

    div class="my-2"
    div class="is-default" data-target="avatar.feedback"
      p class="error too-small" = t(".avatar.errors.small")
      p class="error too-big" = t(".avatar.errors.big")
      p class="error failure" = t(".avatar.errors.failure")
      p class="error img" = t(".avatar.errors.img")
      div class="loading"
        div class="progress progress-bar-striped progress-bar-animated mb-2" style="height: 4px;" data-target="avatar.progress"
          div class="progress-bar" data-target="avatar.value" role="progressbar" style="width: 0;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"

  = f.submit t(".avatar.save"), class: "btn btn-success", data: { target: "avatar.submit" }

app/views/me/avatars/edit.html.slim
div class="col-12 mx-auto col-lg-10 text-center" data-controller="cropper" data-cropper-filename=current_user.original.filename
  div class="btn-group mb-4 d-md-none"
    = link_to t(".cancel"), edit_user_registration_path, class: "btn btn-secondary", data: { target: "cropper.trigger" }
    button class="btn btn-success" data-action="cropper#save" data-target="cropper.trigger" = t(".save")

  div
    = image_tag current_user.original,
      class: "img-fluid",
      crossorigin: "anonymous",
      data: { target: "cropper.image" }

  div class="btn-group mb-4 d-none d-md-block"
    = link_to t(".cancel"), edit_user_registration_path, class: "btn btn-secondary", data: { target: "cropper.trigger" }
    button class="btn btn-success" data-action="cropper#save" data-target="cropper.trigger" = t(".save")