config/routes.rb
Rails.application.routes.draw do
  get "terms", to: "pages#terms"
  get "privacy", to: "pages#privacy"
  get "disclaimer", to: "pages#disclaimer"
  get "noscript", to: "pages#noscript"

  namespace :finder, module: :finders do
    resources :users, only: [:index]
  end

  devise_for :users, path: "sudo", controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  resources :pods, only: [:create, :destroy] do
    resources :attachments, only: [:create], module: :pods
    resources :comments, only: [:create], module: :pods
    resource :reaction, only: [:create, :destroy], module: :pods
  end

  resources :comments, only: [:destroy] do
    resource :reaction, only: [:create, :destroy], module: :comments
  end

  namespace :me do
    resource :avatar, only: [:create, :update, :edit]
    resource :cover, only: [:create]
  end

  scope ":username", as: :user, module: :profiles do
    resource :followers, only: [:show]
    resource :following, only: [:show], controller: :following
    resource :relationship, only: [:create, :destroy]
    resources :pods, only: [:show]
    root "profile#show", as: :profile
  end

  authenticated :user do
    root "home#show"
  end

  root to: "welcome#index"
end

app/views/shared/_followers.html.slim
div id="followers_#{user.id}"
  div class="d-flex text-center justify-content-center"
    = link_to user_following_path(user.username), class: "text-dark"
      div class="text-secondary" = t("common.following")
      div class="font-weight-bold" = user.following_count

    div class="border-right mx-3"

    = link_to user_followers_path(user.username), class: "text-dark"
      div class="text-secondary" = t("common.followers")
      div class="font-weight-bold" = user.followers_count

  - if !current_user.guest? && current_user != user
    - if current_user.following?(user)
      = link_to t("common.unfollow"),
                user_relationship_path(user.username),
                class: "btn btn-outline-primary btn-sm btn-block mt-3",
                method: :delete
    - else
      = link_to t("common.follow"),
                user_relationship_path(user.username),
                class: "btn btn-outline-secondary btn-block btn-sm mt-3",
                method: :post

app/views/shared/_footer.html.slim
div class="col-12 col-lg-3 mb-4 mb-lg-0"
  div class="card"
    div class="card-body d-flex flex-wrap"
      span &copy; 2018 ReddHub
      = link_to t("footer.terms"), terms_path, class: "ml-2"
      = link_to t("footer.privacy"), privacy_path, class: "ml-2"
      = link_to t("footer.disclaimer"), disclaimer_path, class: "ml-2"