config/routes.rb
Rails.application.routes.draw do
  get "terms", to: "pages#terms"
  get "privacy", to: "pages#privacy"
  get "disclaimer", to: "pages#disclaimer"
  get "noscript", to: "pages#noscript"

  namespace :finder, module: :finders do
    resources :users, only: [:index]
  end

  devise_for :users, path: "sudo", controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions",
    unlocks: "users/unlocks"
  }

  resources :pods, only: [:create, :destroy] do
    resources :attachments, only: [:create], module: :pods
    resources :comments, only: [:create], module: :pods
    resource :reaction, only: [:create, :destroy], module: :pods
  end

  resources :comments, only: [:destroy] do
    resource :reaction, only: [:create, :destroy], module: :comments
  end

  namespace :me do
    resource :avatar, only: [:create, :update, :edit]
    resource :cover, only: [:create]
  end

  scope ":username", as: :user, module: :profiles do
    resource :followers, only: [:show]
    resource :following, only: [:show], controller: :following
    resource :relationship, only: [:create, :destroy]
    resources :pods, only: [:show]
    root "profile#show", as: :profile
  end

  authenticated :user do
    root "home#show"
  end

  root to: "welcome#index"
end

app/models/pod.rb
class Pod < ApplicationRecord
  before_validation :preprocess_content
  before_save :markdownfy
  belongs_to :user, counter_cache: true
  has_many :comments, as: :commentable
  has_many :reactions, as: :reactable, dependent: :delete_all
  has_many_attached :images

  with_options unless: :story_format? do |pod|
    pod.validates :content, presence: true
    pod.validates :content, length: { maximum: 280 }
  end

  with_options if: :story_format? do |pod|
    pod.validates :title, length: { maximum: 100 }
    pod.validates :description, length: { maximum: 150 }
    pod.validates :content, length: { maximum: 8000 }
  end

  scope :newest, -> { order(created_at: :desc) }
  scope :no_deleted, -> { where(pending_delete: false) }

  def purge
    update_attribute(:pending_delete, true)
    DestroyPodJob.perform_later(id)
  end

  def story?
    self.kind == Reddhub::Pod::STORY
  end

  def pod?
    self.kind == Reddhub::Pod::POD
  end

  private
    def story_format?
      self.kind == Reddhub::Pod::STORY
    end

    def markdownfy
      return unless @body.present? && story_format?
      self.content_html = ApplicationController.helpers.markdown(@body)
    end

    def check_for_story
      meta = Reddhub::Pod.parse_story(self.content)

      return if meta.nil?

      title, description, @body = meta

      self.title = title
      self.description = description
      self.kind = Reddhub::Pod::STORY
    end

    def preprocess_content
      if content.present?
        self.content = Reddhub::Sanitizer.extra_space(content)
      end

      check_for_story
    end
end

app/controllers/pods/attachments_controller.rb
class Pods::AttachmentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @pod = current_user.pods.find(params[:pod_id])
    pod_attachment = PodAttachment.new(attachments_params)

    respond_to do |format|
      if pod_attachment.attach_to(@pod)
        format.html { redirect_to user_pod_path(current_user.username, @pod) }
        format.json { render @pod, status: :ok }
      else
        format.html { redirect_to root_path }
        format.json { render @pod, status: :unprocessable_entity }
      end
    end
  end

  private

    def attachments_params
      params.require(:pod_attachment).permit(:image)
    end
end

app/controllers/pods/comments_controller.rb
class Pods::CommentsController < CommentsController
  before_action :set_commentable

  private

    def set_commentable
      @commentable = Pod.find(params[:pod_id])
    end
end

app/controllers/pods/reactions_controller.rb
class Pods::ReactionsController < ReactionsController
  before_action :authenticate_user!
  before_action :set_reactable

  private

    def set_reactable
      @reactable = Pod.find(params[:pod_id])
    end
end

app/controllers/pods_controller.rb
class PodsController < ApplicationController
  before_action :authenticate_user!

  def create
    @pod = current_user.pods.new(pod_params)

    respond_to do |format|
      if @pod.save
        format.html do
          redirect_to root_path(current_user.username), notice: t(".notice")
        end
        format.json { render @pod, status: :ok }
      else
        format.html do
          @user = current_user
          @pods = current_user.feed.page(params[:page])
          @reactions = current_user.reactions_for(@pods, "Pod")
          flash.now[:alert] = t(".alert")
          render template: "home/show", layout: "home"
        end
        format.json { render json: @pod.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @pod = current_user.pods.find(params[:id])
    @pod.purge
    redirect_to root_path, notice: t(".notice")
  end

  private

    def pod_params
      params.require(:pod).permit(:content)
    end
end

app/controllers/profiles/pods_controller.rb
class Profiles::PodsController < ApplicationController
  before_action :set_user_by_username
  layout "home"

  def show
    @pod = @user.pods.no_deleted.find(params[:id])
    @comments = @pod.comments.newest.includes(user: [{ avatar_attachment: :blob }]).page(params[:page])
    @reactions = current_user.reactions_for(@comments, "Comment")

    if @pod.story?
      render template: "profiles/stories/show", layout: "empty"
    else
      render
    end
  end
end

app/views/pods/_attachment.html.slim
= form_for PodAttachment.new, url: "/", data: attachment_form_data do |f|

  = f.label :image, class: "btn btn-secondary mb-0", data: { target: "pods--placeholder.attachments" } do
    = icon "far", "image"
    = f.file_field :image,
      accept: "image/x-png,image/jpeg",
      hidden: true,
      data: { action: "pods--attachments#picked", target: "pods--attachments.source pods--placeholder.media" }

  div class="bg-light rounded text-center text-truncate border mt-3 d-none" data-target="pods--attachments.previews"

app/views/pods/_form.html.slim
= simple_form_for(@pod, data: pod_form_data) do |f|
  div class="pods--counter" data-controller="pods--counter"
    div class="word-progress" data-target="pods--counter.progress"
    = f.input :content,
      input_html: { class: "content", rows: 3, data: { action: "keyup->pods--form#word keyup->pods--counter#update blur->pods--placeholder#onBlur", target: "pods--form.source pods--counter.source pods--placeholder.source" } },
      label: false

  = f.submit t(".submit"), class: "btn btn-success float-right", data: { target: "pods--form.submit" }

app/views/pods/_pod.html.slim
li [class="list-group-item list-group-item-action d-flex pod pb-0 px-2 px-md-3"
  data-controller="pod"
  data-pod-url=user_pod_path(pod.user.username, pod)
  data-target="pod.component"
  data-action="click->pod#visit"
  id="pod_#{pod.id}"]
  = image_tag avatar_url(pod.user), class: "rounded-circle mr-2 mr-md-3 avatar-48"
  div class="w-100"
    div class="d-flex justify-content-between"
      = link_to user_profile_path(pod.user.username), class: "h6 text-dark js-action"
        = pod.user.name
        span class="font-weight-normal ml-1" = "@#{pod.user.username}"

      span class="small text-secondary"
        = time_ago_in_words pod.created_at

    - if pod.pod?
      p class="pod-content" = pod.content
      - pod.images.each do |image|
        div class="bg-light rounded text-center border text-truncate js-action"
          = image_tag image, class: "img-fluid js-zoom"
    - else
      div class="rounded border mt-2" style="overflow: hidden;"
        - if pod.images.attached?
          div class="border-bottom" style="width: 100%; height: 0; padding-bottom: 56.25%; position: relative;"
            = image_tag pod.images.first.variant(resize: "500x281^"),
              style: 'width: 100%; height: 100%; position: absolute; object-fit: cover'
        div class="flex-fix-width px-3 py-2"
          h6 class="text-truncate" title=pod.title = pod.title
          p class="m-0" = pod.description

    div class="actions my-2"
      div class="action"
        = render partial: "reactions/action",
                 locals: { reactable: pod, reaction: reaction }
      div class="action"
        = render partial: "comments/action",
                 locals: { pod: pod }
      - if pod.user_id == current_user.id
        div class="action"
          = link_to pod_path(pod), data: { confirm: t(".confirm.destroy") }, method: :delete, class: "btn btn-light btn-action js-action"
            = icon "far", "trash-alt", class: "action-icon"

app/views/pods/_pods.html.slim
ul class="list-group list-group-flush"
  - pods.each do |pod|
    = render partial: "pods/pod",
             locals: { pod: pod, reaction: reactions[pod.id] }